local lsp = {
  "buf_ls",
  "bashls",
  "jsonls",
  "lua_ls",
  "yamlls",
  "marksman",
  "emmet_ls",
  "html",
  "ts_ls",
  "cssls",
  "dockerls",
  "docker_compose_language_service",
  "gopls",
}

_G.servers = {
  lsp = lsp,
  mason_lsp = lsp,
  null_ls = {
    "codespell",
    "fish_indent",
    "fish",
    "checkmake",
    "hadolint",
    "revive",
    "shfmt",
    "stylua",
    "markdownlint",
    "gofumpt",
    "goimports",
    "buf",
    "golines",
    "gomodifytags",
    "impl",
    "prettier",
    "spell",
    "yamllint",
    "golangci_lint",
  },
  sources_null_ls = function()
    local builtins = require("null-ls").builtins
    return {
      builtins.diagnostics.codespell,
      builtins.diagnostics.fish,
      builtins.diagnostics.checkmake,
      builtins.diagnostics.hadolint,
      builtins.diagnostics.revive,
      builtins.diagnostics.buf,
      builtins.code_actions.gomodifytags,
      builtins.code_actions.impl,
      builtins.formatting.fish_indent,
      builtins.formatting.shfmt,
      builtins.formatting.stylua,
      builtins.formatting.markdownlint,
      builtins.formatting.gofumpt,
      builtins.formatting.goimports,
      builtins.formatting.buf,
      builtins.formatting.prettier,
      builtins.completion.spell,
      builtins.diagnostics.yamllint,
      builtins.formatting.golines.with({
        extra_args = {
          "--max-len=180",
          "--base-formatter=gofumpt",
        },
      }),
      builtins.diagnostics.golangci_lint.with({
        extra_args = {
          "--enable=revive,gosec,misspell",
          "--allow-parallel-runners",
        },
      }),
    }
  end,
  dap = { "delve" },
}
