new_abbr dcu "docker compose up -d"
new_abbr dcd "docker compose down"
new_abbr dcp "docker compose ps -a"
new_abbr dcl "docker compose logs -f"
new_abbr dkl "docker logs -f"
new_abbr dkier "docker exec -it -exec --rm % -- sh"
new_abbr dkie "docker exec -it -exec % -- sh"
new_abbr dkia "docker image ls -a"
new_abbr dkca "docker container ls -a"
