new_abbr gomi "go install github.com/imkk000/%@latest"
new_abbr goi "go install %@latest"
new_abbr gog "go get -u"
new_abbr gob "go build -ldflags='-w -s' -o"
new_abbr gomd "go mod tidy"

new_abbr_go gopackages "golang.org/x/tools/go/packages"
new_abbr_go cloudflare "github.com/cloudflare/cloudflare-go/v4"
new_abbr_go cobra "github.com/spf13/cobra"
new_abbr_go color "github.com/fatih/color"
new_abbr_go cron "github.com/robfig/cron/v3"
new_abbr_go dotenv "github.com/joho/godotenv"
new_abbr_go echo "github.com/labstack/echo/v4"
new_abbr_go envconfig "github.com/kelseyhightower/envconfig"
new_abbr_go fasthttp "github.com/valyala/fasthttp"
new_abbr_go fiber "github.com/gofiber/fiber/v2"
new_abbr_go gin "github.com/gin-gonic/gin"
new_abbr_go git "github.com/go-git/go-git/v5"
new_abbr_go gitlab "gitlab.com/gitlab-org/api/client-go"
new_abbr_go godump "github.com/goforj/godump"
new_abbr_go goquery "github.com/PuerkitoBio/goquery"
new_abbr_go kafka "github.com/confluentinc/confluent-kafka-go/v2"
new_abbr_go mongo "go.mongodb.org/mongo-driver/mongo/v2"
new_abbr_go mongo1 "go.mongodb.org/mongo-driver/mongo"
new_abbr_go redis "github.com/redis/rueidis"
new_abbr_go resty "github.com/go-resty/resty/v2"
new_abbr_go testify "github.com/stretchr/testify"
new_abbr_go urfavecli "github.com/urfave/cli/v3"
new_abbr_go uuid "github.com/google/uuid"
new_abbr_go viper "github.com/spf13/viper"
new_abbr_go websocket "github.com/gorilla/websocket"
new_abbr_go yaml "github.com/goccy/go-yaml"
new_abbr_go zerolog "github.com/rs/zerolog"
new_abbr_go mapstructure "github.com/go-viper/mapstructure/v2"
new_abbr_go protoparser "github.com/yoheimuta/go-protoparser/v4"
new_abbr_go gocases "golang.org/x/text/cases"
new_abbr_go golanguage "golang.org/x/text/language"
